<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.0.309
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Get Quote Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'afrimations@gmail.com',
		'to' => 'afrimations@gmail.com'
	),
	'fields' => array(
		'custom_U1074' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Your name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Your name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email Address\' is required.',
				'format' => 'Field \'Email Address\' has an invalid email.'
			)
		),
		'custom_U1056' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U1060' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'State/Province',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State/Province\' is required.'
			)
		),
		'custom_U1078' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Country',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Country\' is required.'
			)
		),
		'custom_U1082' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Type in anything you\'d like us to know',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Type in anything you\'d like us to know\' is required.'
			)
		),
		'custom_U1091' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Custom Request',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1127' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'Urgent Request',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
